### ISSUE TITLE
Some zone ID have changed

### ISSUE THREAD

**Issue by Evolena** [Esteren/EsterenMapsTiddlyWiki#27]
We already had the case (corrected in #11) of IDs that have "jumped" at creation from the script (leaving unemployed IDs), and later that have moved to fill the gaps (I'm not clear I fear...) on the map/DB.

It has happened again:
- Cirque d'Argoneskan : 54 -> 47
- Failles Hurlantes : 55 -> 48
- Golfe de Reizh : 57 -> 50 (I've spotted this one first, as the ID for the new Royaume de Reizh is 57 too)
- Marais du Ponant : 58 -> 51

46 (L'archipel des Trois Sœurs), 49 (Forêt de Taelwald) and 52 (Région d'Abondance) have not moved (they were corrected in #11 ).
53 didn't and still doesn't exist, while 54 and 55 do not longer exist (that means 3 potential issues in the future).
56 have been filled by Royaume de Gwidre, and 57 by the Royaume de Reizh.

I was on the point to send a PR for the "guarded" field (see https://github.com/Evolena/EsterenMapsTiddlyWiki/commit/6885155bec50e94d8b0d514a11be4069dbcb0bf5 . A lot of changes (guarded field + cascading the Royaumes ID in zoneparent_id field + status of some zones), but it is comparable in Notepad++). Do I correct that manually before sending you the PR ?

**Comment by Pierstoval** [comment]
Nope, make the PR, I'll get a prod database and test in my local env to check why the IDs are wrong, and to see whether I change them manually or the script would do it automatically

**Comment by Pierstoval** [comment]
This one seems correct :confused: , so it seems that it's the tiddlers file that's incorrect...

![capture d ecran 2015-11-06 a 13 53 40](https://cloud.githubusercontent.com/assets/3369266/10997491/d74e54f0-848d-11e5-91d2-aad62200ae40.png)

Maybe update the tiddlers file then... I'll send you a webservice export of all datas soon through redmine
